In [7]:
import numpy as np
import random
import pygame
import sys
import math
import pickle
import pandas as pd
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_curve, roc_auc_score
from sklearn.metrics import confusion_matrix
import seaborn as sns
import math

BLUE = (0,0,255)
BLACK = (0,0,0)
RED = (255,0,0)
YELLOW = (255,255,0)

ROW_COUNT = 6
COLUMN_COUNT = 7

PLAYER = 0
AI = 1

EMPTY = 0
PLAYER_PIECE = 1
AI_PIECE = 2

WINDOW_LENGTH = 4

def create_board():
    board = np.zeros((ROW_COUNT,COLUMN_COUNT))
    return board

def drop_piece(board, row, col, piece):
    board[row][col] = piece
    
def is_valid_location(board, col):
    return board[ROW_COUNT-1][col] == 0

def get_next_open_row(board, col):
    for r in range(ROW_COUNT):
        if board[r][col] == 0:
            return r
        
def print_board(board):
    print(np.flip(board, 0))
    
def winning_move(board, piece):
    # Check horizontal locations for win
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT):
            if board[r][c] == piece and board[r][c+1] == piece and board[r][c+2] == piece and board[r][c+3] == piece:
                return True

    # Check vertical locations for win
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT-3):
            if board[r][c] == piece and board[r+1][c] == piece and board[r+2][c] == piece and board[r+3][c] == piece:
                return True

    # Check positively sloped diaganols
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT-3):
            if board[r][c] == piece and board[r+1][c+1] == piece and board[r+2][c+2] == piece and board[r+3][c+3] == piece:
                return True

    # Check negatively sloped diaganols
    for c in range(COLUMN_COUNT-3):
        for r in range(3, ROW_COUNT):
            if board[r][c] == piece and board[r-1][c+1] == piece and board[r-2][c+2] == piece and board[r-3][c+3] == piece:
                return True
            
def evaluate_window(window, piece):
    score = 0
    opp_piece = PLAYER_PIECE
    if piece == PLAYER_PIECE:
        opp_piece = AI_PIECE

    if window.count(piece) == 4:
        score += 100
    elif window.count(piece) == 3 and window.count(EMPTY) == 1:
        score += 5
    elif window.count(piece) == 2 and window.count(EMPTY) == 2:
        score += 2

    if window.count(opp_piece) == 3 and window.count(EMPTY) == 1:
        score -= 4

    return score

def score_position(board, piece):
    score = 0

    ## Score center column
    center_array = [int(i) for i in list(board[:, COLUMN_COUNT//2])]
    center_count = center_array.count(piece)
    score += center_count * 3

    ## Score Horizontal
    for r in range(ROW_COUNT):
        row_array = [int(i) for i in list(board[r,:])]
        for c in range(COLUMN_COUNT-3):
            window = row_array[c:c+WINDOW_LENGTH]
            score += evaluate_window(window, piece)

    ## Score Vertical
    for c in range(COLUMN_COUNT):
        col_array = [int(i) for i in list(board[:,c])]
        for r in range(ROW_COUNT-3):
            window = col_array[r:r+WINDOW_LENGTH]
            score += evaluate_window(window, piece)

    ## Score posiive sloped diagonal
    for r in range(ROW_COUNT-3):
        for c in range(COLUMN_COUNT-3):
            window = [board[r+i][c+i] for i in range(WINDOW_LENGTH)]
            score += evaluate_window(window, piece)

    for r in range(ROW_COUNT-3):
        for c in range(COLUMN_COUNT-3):
            window = [board[r+3-i][c+i] for i in range(WINDOW_LENGTH)]
            score += evaluate_window(window, piece)

    return score

def is_terminal_node(board):
    return winning_move(board, PLAYER_PIECE) or winning_move(board, AI_PIECE) or len(get_valid_locations(board)) == 0

def get_valid_locations(board):
    valid_locations = []
    for col in range(COLUMN_COUNT):
        if is_valid_location(board, col):
            valid_locations.append(col)
    return valid_locations

def pick_best_move(board, piece):

    valid_locations = get_valid_locations(board)
    best_score = -10000
    best_col = random.choice(valid_locations)
    for col in valid_locations:
        row = get_next_open_row(board, col)
        temp_board = board.copy()
        drop_piece(temp_board, row, col, piece)
        score = score_position(temp_board, piece)
        if score > best_score:
            best_score = score
            best_col = col

    return best_col

def draw_board(board):
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):
            pygame.draw.rect(screen, BLUE, (c*SQUARESIZE, r*SQUARESIZE+SQUARESIZE, SQUARESIZE, SQUARESIZE))
            pygame.draw.circle(screen, BLACK, (int(c*SQUARESIZE+SQUARESIZE/2), int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)), RADIUS)

    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):
            if board[r][c] == PLAYER_PIECE:
                pygame.draw.circle(screen, RED, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
            elif board[r][c] == AI_PIECE: 
                pygame.draw.circle(screen, YELLOW, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
    pygame.display.update()
    

def minimax(board, depth, alpha, beta, maximizingPlayer):
    valid_locations = get_valid_locations(board)
    is_terminal = is_terminal_node(board)
    if depth == 0 or is_terminal:
        if is_terminal:
            if winning_move(board, AI_PIECE):
                return (None, 100000000000000)
            elif winning_move(board, PLAYER_PIECE):
                return (None, -10000000000000)
            else: # Game is over, no more valid moves
                return (None, 0)
        else: # Depth is zero
            return (None, score_position(board, AI_PIECE))
    if maximizingPlayer:
        value = -math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            b_copy = board.copy()
            drop_piece(b_copy, row, col, AI_PIECE)
            new_score = minimax(b_copy, depth-1, alpha, beta, False)[1]
            if new_score > value:
                value = new_score
                column = col
            alpha = max(alpha, value)
            if alpha >= beta:
                break
        return column, value

    else: # Minimizing player
        value = math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            b_copy = board.copy()
            drop_piece(b_copy, row, col, PLAYER_PIECE)
            new_score = minimax(b_copy, depth-1, alpha, beta, True)[1]
            if new_score < value:
                value = new_score
                column = col
            beta = min(beta, value)
            if alpha >= beta:
                break
        return column, value

# Generate Optimal Move Data

In [21]:
data =  pd.read_csv('connectfour.data', sep=",",header=None)
data = data.iloc[: , :-1]

In [22]:
data

0  1  2  3  4  5  6  7  8  9   ... 32 33 34 35 36 37 38 39 40 41
0      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
1      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
2      b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
3      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
4      o  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b  b
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
67552  x  x  b  b  b  b  o  x  o  b  ...  b  b  b  b  o  o  x  b  b  b
67553  x  x  b  b  b  b  o  b  b  b  ...  b  b  b  b  o  x  o  o  x  b
67554  x  x  b  b  b  b  o  o  b  b  ...  b  b  b  b  o  x  x  o  b  b
67555  x  o  b  b  b  b  o  b  b  b  ...  b  b  b  b  o  x  o  x  x  b
67556  x  o  o  o  x  b  o  b  b  b  ...  b  b  b  b  x  b  b  b  b  b

[67557 rows x 42 columns]

In [65]:
#Label encoding
le = preprocessing.LabelEncoder()


col=data.columns.tolist()
print(col)


#Transforming X
for i in range(len(col)):
    data[col[i]]=le.fit_transform(data[col[i]])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41]


In [66]:
data

0   1   2   3   4   5   6   7   8   9   ...  32  33  34  35  36  37  \
0       0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
1       0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
2       0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   
3       0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
4       1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
67552   2   2   0   0   0   0   1   2   1   0  ...   0   0   0   0   1   1   
67553   2   2   0   0   0   0   1   0   0   0  ...   0   0   0   0   1   2   
67554   2   2   0   0   0   0   1   1   0   0  ...   0   0   0   0   1   2   
67555   2   1   0   0   0   0   1   0   0   0  ...   0   0   0   0   1   2   
67556   2   1   1   1   2   0   1   0   0   0  ...   0   0   0   0   2   0   

       38  39  40  41  
0       0   0   0   0  
1       0   0   0   0  
2       0   0   0   0  
3       0   0   0   0  
4       0   0   0   0  
...    ..  ..  ..  ..  
67552   2   0   0   0  
67553   1   1   2   0  
67554   2   1   0   0  
67555   1   2   2   0  
67556   0   0   0   0  

[67557 rows x 42 columns]

Blank - 0, Player X - 2, Player O - 1

In [67]:
final = []
for i in range(0,67557):
    arr=[]
    arr.append(list(data.iloc[i,0:6]))
    arr.append(list(data.iloc[i,6:12]))
    arr.append(list(data.iloc[i,12:18]))
    arr.append(list(data.iloc[i,18:24]))
    arr.append(list(data.iloc[i,24:30]))
    arr.append(list(data.iloc[i,30:36]))
    arr.append(list(data.iloc[i,36:42]))

    final.append(np.flip(np.array(arr).T,axis=0))

In [68]:
print(final[0])

[[0 0 0 1 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 1 1 0 0 0]
 [0 0 2 2 0 0 0]]


In [69]:
arr = []
for i in range(67556):
    arr.append(minimax(final[i], 5, -math.inf, math.inf, True))

In [71]:
arr

[(4, 27),
 (0, 17),
 (4, 25),
 (4, 27),
 (4, 27),
 (4, 29),
 (4, 23),
 (2, 27),
 (4, 27),
 (2, 29),
 (2, 27),
 (2, 29),
 (4, 23),
 (2, 25),
 (2, 23),
 (2, 25),
 (2, 25),
 (2, 25),
 (1, 29),
 (0, 23),
 (4, 28),
 (4, 32),
 (4, 30),
 (4, 30),
 (0, 25),
 (6, 23),
 (0, 22),
 (4, 25),
 (4, 27),
 (4, 27),
 (0, 25),
 (0, 17),
 (0, 17),
 (0, 17),
 (0, 15),
 (6, 17),
 (0, 15),
 (4, 19),
 (0, 17),
 (4, 22),
 (4, 23),
 (4, 23),
 (0, 23),
 (6, 25),
 (4, 26),
 (4, 25),
 (4, 27),
 (4, 23),
 (1, 19),
 (6, 15),
 (4, 21),
 (4, 22),
 (4, 23),
 (1, 21),
 (0, 21),
 (0, 23),
 (4, 21),
 (4, 25),
 (4, 23),
 (2, 31),
 (2, 33),
 (2, 34),
 (2, 34),
 (4, 23),
 (6, 22),
 (4, 23),
 (4, 25),
 (0, 23),
 (2, 26),
 (0, 25),
 (2, 25),
 (2, 25),
 (2, 23),
 (4, 21),
 (2, 22),
 (0, 20),
 (2, 24),
 (2, 23),
 (2, 23),
 (2, 27),
 (2, 29),
 (2, 30),
 (2, 28),
 (2, 23),
 (2, 24),
 (2, 23),
 (2, 25),
 (0, 23),
 (2, 26),
 (2, 25),
 (2, 30),
 (2, 30),
 (4, 25),
 (4, 27),
 (4, 27),
 (1, 25),
 (2, 27),
 (2, 24),
 (4, 27),
 (2, 28),


In [80]:
d = pd.DataFrame(arr)
d.iloc[:,0].unique()

array([ 4.,  0.,  2.,  1.,  6.,  5., nan,  3.])

In [74]:
d.to_csv('generated_data_y.csv')

# Loading mlp pkl and running the final game code

In [20]:
# load the pkl model
filename = 'final_mlp_model.pkl'
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model

Pipeline(steps=[('mlpclassifier',
                 MLPClassifier(hidden_layer_sizes=(150, 100, 50), tol=0.5))])

In [23]:
np.flip(board,axis=0).T.reshape(1,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
board = create_board()
print_board(board)
game_over = False

pygame.init()

SQUARESIZE = 100

width = COLUMN_COUNT * SQUARESIZE
height = (ROW_COUNT+1) * SQUARESIZE

size = (width, height)

RADIUS = int(SQUARESIZE/2 - 5)

screen = pygame.display.set_mode(size)
draw_board(board)
pygame.display.update()

myfont = pygame.font.SysFont("monospace", 75)

turn = random.randint(PLAYER, AI)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [22]:
while not game_over:

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()

        if event.type == pygame.MOUSEMOTION:
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
            posx = event.pos[0]
            if turn == PLAYER:
                pygame.draw.circle(screen, RED, (posx, int(SQUARESIZE/2)), RADIUS)

        pygame.display.update()

        if event.type == pygame.MOUSEBUTTONDOWN:
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
            #print(event.pos)
            # Ask for Player 1 Input
            if turn == PLAYER:
                posx = event.pos[0]
                col = int(math.floor(posx/SQUARESIZE))

                if is_valid_location(board, col):
                    row = get_next_open_row(board, col)
                    drop_piece(board, row, col, PLAYER_PIECE)

                    if winning_move(board, PLAYER_PIECE):
                        label = myfont.render("Player wins!!", 1, RED)
                        screen.blit(label, (40,10))
                        game_over = True

                    turn += 1
                    turn = turn % 2

                    print_board(board)
                    draw_board(board)


    # # Ask for Player 2 Input
    if turn == AI and not game_over:				

        #col = random.randint(0, COLUMN_COUNT-1)
        #col = pick_best_move(board, AI_PIECE)
        #col, minimax_score = minimax(board, 5, -math.inf, math.inf, True)
        col = int(loaded_model.predict(np.flip(board,axis=0).T.reshape(1,-1))[0])
        print(col)
        
        if is_valid_location(board, col):
            #pygame.time.wait(500)
            row = get_next_open_row(board, col)
            drop_piece(board, row, col, AI_PIECE)

            if winning_move(board, AI_PIECE):
                label = myfont.render("Computer wins!!", 1, YELLOW)
                screen.blit(label, (40,10))
                game_over = True

            print_board(board)
            draw_board(board)

            turn += 1
            turn = turn % 2

    if game_over:
        pygame.time.wait(5000)

C:\Users\sjalu\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(


3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 1.]]
3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 1.]]


C:\Users\sjalu\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 1. 0. 2. 0. 0. 1.]]
3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 1. 0. 2. 0. 0. 1.]]


C:\Users\sjalu\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 1. 0. 2. 1. 0. 1.]]
3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 1. 0. 2. 1. 0. 1.]]


C:\Users\sjalu\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
